-- MySQL Script generated by MySQL Workbench
-- Thu Jan 19 22:26:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema resilia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema resilia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `resilia` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `resilia` ;

-- -----------------------------------------------------
-- Table `resilia`.`alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`alunos` (
  `id_aluno` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_aluno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `resilia`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `duracao` TIME NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `resilia`.`matriculas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`matriculas` (
  `id_matriculas` INT NOT NULL AUTO_INCREMENT,
  `id_alunos` INT NOT NULL,
  `id_cursos` INT NOT NULL,
  `data_de_matricula` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_matriculas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `resilia`.`alunos_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`alunos_cursos` (
  `id_alunos_cursos` INT NOT NULL AUTO_INCREMENT,
  `id_alunos` INT NOT NULL,
  `id_cursos` INT NOT NULL,
  `matriculas_id_matriculas` INT NOT NULL,
  PRIMARY KEY (`id_alunos_cursos`),
  INDEX `fk_id_aluno_idx` (`id_alunos` ASC) VISIBLE,
  INDEX `fk_id_curso_idx` (`id_cursos` ASC) VISIBLE,
  INDEX `fk_alunos_cursos_matriculas1_idx` (`matriculas_id_matriculas` ASC) VISIBLE,
  CONSTRAINT `fk_id_aluno`
    FOREIGN KEY (`id_alunos`)
    REFERENCES `resilia`.`alunos` (`id_aluno`),
  CONSTRAINT `fk_id_curso`
    FOREIGN KEY (`id_cursos`)
    REFERENCES `resilia`.`cursos` (`id_curso`),
  CONSTRAINT `fk_alunos_cursos_matriculas1`
    FOREIGN KEY (`matriculas_id_matriculas`)
    REFERENCES `resilia`.`matriculas` (`id_matriculas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `resilia`.`disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`disciplinas` (
  `id_disciplina` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `duracao` TIME NOT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `cursos_id_curso` INT NOT NULL,
  PRIMARY KEY (`id_disciplina`),
  INDEX `fk_disciplinas_cursos1_idx` (`cursos_id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_disciplinas_cursos1`
    FOREIGN KEY (`cursos_id_curso`)
    REFERENCES `resilia`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `resilia`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`notas` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `id_aluno_curso` INT NOT NULL,
  `nota` DECIMAL(5,2) NOT NULL,
  `comentario` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_nota`),
  INDEX `fk_aluno_curso_idx` (`id_aluno_curso` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_curso`
    FOREIGN KEY (`id_aluno_curso`)
    REFERENCES `resilia`.`alunos_cursos` (`id_alunos_cursos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `resilia`.`professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`professores` (
  `id_professor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `endereco` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(20) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  `cep` INT NULL DEFAULT NULL,
  `disciplinas_id_disciplina` INT NOT NULL,
  PRIMARY KEY (`id_professor`),
  INDEX `fk_professores_disciplinas1_idx` (`disciplinas_id_disciplina` ASC) VISIBLE,
  CONSTRAINT `fk_professores_disciplinas1`
    FOREIGN KEY (`disciplinas_id_disciplina`)
    REFERENCES `resilia`.`disciplinas` (`id_disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `resilia`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resilia`.`turmas` (
  `id_turmas` INT NOT NULL AUTO_INCREMENT,
  `turno` VARCHAR(5) NULL DEFAULT NULL,
  `inicio` DATE NULL DEFAULT NULL,
  `fim` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_turmas`),
  CONSTRAINT `fk_id_turmas_curso`
    FOREIGN KEY (`id_turmas`)
    REFERENCES `resilia`.`cursos` (`id_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
